name: secret_scan
on:
  pull_request:
    branches:
       - 'main'
  push:
    branches:
       - 'main'

permissions: 
  contents: read
  issues: write

jobs:
  scan_secrets_on_pull_request:
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == github.event.repository.default_branch
    uses: opentok/application-security-secret-scanner/.github/workflows/secret_scanner_on_pr.yml@main
    
  scan_secrets_on_push:
    if: github.event_name == 'push' && github.ref_name == github.event.repository.default_branch
    uses: opentok/application-security-secret-scanner/.github/workflows/secret_scanner_on_push.yaml@main 
